kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/version: "1.0.0"
  name: {{ .Chart.Name }}-{{ .Release.Name }}-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: {{ .Chart.Name }}-{{ .Release.Name }}
  type: ClusterIP
